sudo: required
language: dart
dart:
  - stable
addons:
  chrome: stable
env:
  - TEST_ENV="travis"
with_content_shell: true
script:
  - bash tool/travis.bash
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov
