sudo: required
language: dart
dart:
  - stable
addons:
  chrome: stable
cache:
  directories:
    - .dart_tool/build
script:
  - TEST_ENV="travis" bash ./tool/travis.bash
#  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov # TODO: add this back in when coverage is setup
