name: history
version: 0.2.1
description: Abstraction of HTML5 History API for use in any environment. Control session history with ease!
author: Srinivas Dhanwada <dhanwada.dev@gmail.com>
homepage: https://github.com/pr1sm/history_dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  quiver: '>=0.14.0 <3.0.0'
dev_dependencies:
  coverage: ^0.12.0
  dartdoc: ^0.20.0
  dart_style: ^1.0.7
  dependency_validator: ^1.1.0
  mockito: ^3.0.0
  shelf: ^0.7.3
  shelf_proxy: ^0.1.0
  test: ^1.0.0
  version: ^1.0.3
transformers:
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
