name: history
version: 1.0.1
description: Abstraction of HTML5 History API for use in any environment. Control session history with ease!
author: Srinivas Dhanwada <dhanwada.dev@gmail.com>
homepage: https://github.com/pr1sm/history_dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  quiver: '>=0.14.0 <3.0.0'
dev_dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_test: ^0.10.3+3
  build_web_compilers: '>=0.3.6 <0.5.0'
  coverage: ^0.12.0
  dartdoc: '>=0.24.0 <1.0.0'
  dart_style: ^1.0.7
  dependency_validator: ^1.1.0
  mockito: ^4.0.0
  pedantic: ^1.0.0
  shelf: ^0.7.3
  shelf_proxy: ^0.1.0
  test: ^1.0.0
  version: ^1.0.3
  webdev: ^1.0.0

