name: history
version: 0.2.0
description: Abstraction of HTML5 History API for use in any environment
author: Srinivas Dhanwada <dhanwada.dev@gmail.com>
homepage: https://github.com/pr1sm/history_dart
environment:
  sdk: ">=1.24.0 <2.0.0"
dependencies:
  quiver: ^0.29.0
dev_dependencies:
  browser: ^0.10.0
  coverage: '>=0.9.3 <0.11.0'
  dartdoc: '>=0.14.1 <0.19.0'
  dart_dev: ^1.9.2
  dart_style: ^1.0.7
  dependency_validator: ^1.1.0
  mockito: ^2.2.2
  shelf: ^0.7.3
  shelf_proxy: ^0.1.0
  test: ^0.12.32+1
  version: ^1.0.3
transformers:
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
