@TestOn('browser || vm')
library test.unit.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/unit/ -e Environment.both --no-genHtml`

import './utils/path_utils_test.dart' as utils_path_utils_test;
import 'package:test/test.dart';

void main() {
  utils_path_utils_test.main();
}