@TestOn('browser || vm')
library test.unit.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/unit/ -e Environment.both --no-genHtml`

import './location_test.dart' as location_test;
import './transition_manager_test.dart' as transition_manager_test;
import './utils/dom_utils_test.dart' as utils_dom_utils_test;
import './utils/hash_utils_test.dart' as utils_hash_utils_test;
import './utils/path_utils_test.dart' as utils_path_utils_test;
import './utils/utils_test.dart' as utils_utils_test;
import 'package:test/test.dart';

void main() {
  location_test.main();
  transition_manager_test.main();
  utils_dom_utils_test.main();
  utils_hash_utils_test.main();
  utils_path_utils_test.main();
  utils_utils_test.main();
}